name: expense_tracker
description: A secure expense tracking Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_analytics: ^10.8.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.2  # ✅ Stable version
  google_fonts: ^6.1.0
  email_validator: ^2.1.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/